### ISSUE TITLE
instagram story anonymity guard marks a lot of other stories as "seen"?

### ISSUE THREAD

**Issue by arig241** [baturkacamak/user-scripts#14]
In the recent couple of days blocking the "ViewSeenAt" keep the current viewed story from being marked as seen, yet marks the following stories of the next 3 or 4 account as "seen". I have not managed to find out what requests exactly is responsible for this behavior, and wondering if that's happens universally or if there are any insights

**Comment by baturkacamak** [comment]
Hey @arig241,

Thank you for bringing this to my attention.

I've taken your feedback and have made some updates to the user script. The primary change addresses the issue of unintended "seen" markings on the following stories.

It would be helpful if you could test the updated script on your end to verify if the issue persists.

I appreciate your feedback.
